<h1>Sesi 4<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Numpy-Introduction" data-toc-modified-id="Numpy-Introduction-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Numpy Introduction</a></span></li><li><span><a href="#Creating-Array" data-toc-modified-id="Creating-Array-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Creating Array</a></span></li><li><span><a href="#Add,-Remove,-and-Sort" data-toc-modified-id="Add,-Remove,-and-Sort-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Add, Remove, and Sort</a></span></li><li><span><a href="#Shape-and-size" data-toc-modified-id="Shape-and-size-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Shape and size</a></span></li><li><span><a href="#Reshape" data-toc-modified-id="Reshape-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Reshape</a></span></li><li><span><a href="#Convert-1D-to-2D" data-toc-modified-id="Convert-1D-to-2D-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Convert 1D to 2D</a></span></li><li><span><a href="#Indexing-and-Slicing" data-toc-modified-id="Indexing-and-Slicing-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Indexing and Slicing</a></span></li><li><span><a href="#Creating-Array-from-Existing-Data" data-toc-modified-id="Creating-Array-from-Existing-Data-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Creating Array from Existing Data</a></span></li><li><span><a href="#Basic-array-operations" data-toc-modified-id="Basic-array-operations-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Basic array operations</a></span></li><li><span><a href="#Broadcasting" data-toc-modified-id="Broadcasting-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Broadcasting</a></span></li><li><span><a href="#More-Array-Operations" data-toc-modified-id="More-Array-Operations-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>More Array Operations</a></span></li><li><span><a href="#Matrices" data-toc-modified-id="Matrices-12"><span class="toc-item-num">12&nbsp;&nbsp;</span>Matrices</a></span></li><li><span><a href="#Creating-Matrices" data-toc-modified-id="Creating-Matrices-13"><span class="toc-item-num">13&nbsp;&nbsp;</span>Creating Matrices</a></span></li><li><span><a href="#Matrix-Arithmetic" data-toc-modified-id="Matrix-Arithmetic-14"><span class="toc-item-num">14&nbsp;&nbsp;</span>Matrix Arithmetic</a></span></li><li><span><a href="#Dot-Product" data-toc-modified-id="Dot-Product-15"><span class="toc-item-num">15&nbsp;&nbsp;</span>Dot Product</a></span></li><li><span><a href="#Matrix-Indexing" data-toc-modified-id="Matrix-Indexing-16"><span class="toc-item-num">16&nbsp;&nbsp;</span>Matrix Indexing</a></span></li><li><span><a href="#Matrix-Aggregation" data-toc-modified-id="Matrix-Aggregation-17"><span class="toc-item-num">17&nbsp;&nbsp;</span>Matrix Aggregation</a></span></li><li><span><a href="#Transposing-and-Reshaping" data-toc-modified-id="Transposing-and-Reshaping-18"><span class="toc-item-num">18&nbsp;&nbsp;</span>Transposing and Reshaping</a></span></li><li><span><a href="#N-Dimensional-Array" data-toc-modified-id="N-Dimensional-Array-19"><span class="toc-item-num">19&nbsp;&nbsp;</span>N-Dimensional Array</a></span></li><li><span><a href="#Flatten-N-Dimensional-Array" data-toc-modified-id="Flatten-N-Dimensional-Array-20"><span class="toc-item-num">20&nbsp;&nbsp;</span>Flatten N-Dimensional Array</a></span></li></ul></div>

# Numpy Introduction

Numpy (Numerical Python) untuk data numerik. Inti eksositem ilmiah python. Pustaka 
numpy berisi multidimensi (multidimensional array) dan struktur data matriks. Numpy 
menyediakan ndarray, objek array n-dimensi homogen.

**What is array?**

Array adalah stuktur data central dari peprustakan numpy. Array adalah grid of values dan 
berisi informasi tentang data mentah, cara menemukan elemen dan mempersentasikan elemen.
Array dapat diindeks oleh tuple dri bilangan non negatif, boolean, atau bilangan bulat.

Pengindeksan Numpy dimulai dari 0. artinya jika kalian mengakses elemen pertama dalam array, kalian mengakses elemen "0"

In [8]:
[[0., 0., 0],
 [1., 1., 1.]]

[[0.0, 0.0, 0], [1.0, 1.0, 1.0]]

Array diatas memiliki 2 axes (dimensi). Axis pertama panjangnya 2. axis kedua panjang 3

# Creating Array 

In [15]:
import numpy as np
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

Numpy menyediakan metode seperti ones(), zeros, dan lain2

In [18]:
# you can easily create an array filled with 0s:

np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [19]:
# On array filled with 1s:

np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [20]:
# or even an empty array!
# the function empty creates an array whose initial content is random and depends on the state of the memory

np.empty(6)
np.empty(2)

array([1.69759663e-313, 8.48798317e-314])

In [22]:
# you can create an array with a range of elements

print(np.arange(6))
print(np.arange(0,10,2))
print(np.arange(10,2,-2))
print(np.arange(2,10,3))


[0 1 2 3 4 5]
[0 2 4 6 8]
[10  8  6  4]
[2 5 8]


apa yang dilakukan arange([start], stop,[step]) adalah mengatur angka dari awal sampai berhenti. 

# Add, Remove, and Sort

Menambhakn elemen ke array dengan **np.arrayppend()**

In [25]:
arr = np.array([1,2,3,4,5,6,7,8])
np.append(arr,[1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

Kalian bisa menghapus elemen dengan **np.delete()**

In [27]:
np.delete(arr,1)

array([1, 3, 4, 5, 6, 7, 8])

Mengurutkan elemen dengan **np.sort()**

In [29]:
brr= np.array([11,4,2,19,27])
np.sort(brr)

array([ 2,  4, 11, 19, 27])

# Shape and size

In [32]:
ar =  np.array([[[0,1,2,3],
                 [4,5,6,7]],

                 [[0,1,2,3],
                  [4,5,6,7]],

                 [[0,1,2,3],
                  [4,5,6,7]]])
print(ar)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


**ar.nidm** akan memberi tahu jumlah axes/dimensi dari array

In [35]:
ar.ndim

3

**ar.size** akan memberi tahu kalian jumlah total elemen array

In [34]:
ar.size

24

ar.shape akan menampilkan tuple integer yang menunjukan jumlah elemen yang akan disimpan di sepanjang setiap dimensi array

In [37]:
ar.shape

(3, 2, 4)

In [38]:
arr_one = np.array([[1,2,3,4,5]])

In [39]:
arr_one.ndim

2

In [40]:
arr_one.size

5

In [41]:
arr_one.shape

(1, 5)

# Reshape

reshape() akan memberikan bentuk baru ke array tanpa mengubah datanya. 

In [45]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [46]:
print("contoh reshape 3,2")
b = a.reshape(3,2)
print(b)

contoh reshape 3,2
[[0 1]
 [2 3]
 [4 5]]


In [47]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

Dengan np.reshape kalian akan dapat menentukan beberapa parameter opsional:

**np.reshape(a, newshape, order)**
1. a : array yang akan direshaped
2. newshape : bentuk baru yang kalian inginkan. kalian dapat menetukan integer atau tuple integer.
3. order

# Convert 1D to 2D

np.newaxis akan meningkatkan dimensi array kalian sebesar satu dimensi bila diguanakn sekali. Srtinya array 1D akan menajdi 2D

In [48]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [50]:
# You can use np.newaxis to add a new axis
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [51]:
# U can convert 1d to a row vector by inserting an azis along the first dimension
row_vector=a[np.newaxis, :]
print(row_vector.shape)
print(row_vector) 

(1, 6)
[[1 2 3 4 5 6]]


In [52]:
# For a column vector, u can insert an axis along the second dimension
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


Kalian juga dapat memperluas array dengan mamasukkan axis baru kepada posisi yang ditentukan dengan **np.expand_dims**

In [54]:
a = np.array([1,2,3,4,5,6])
print(a.shape)

(6,)


In [56]:
# You can use np.expand_dims to add an axis at index position 1 with:
b = np.expand_dims(a, axis=1)
print(b.shape)

(6, 1)


In [58]:
# You can use np.expand_dims to add an axis at index position 0 with:
c = np.expand_dims(a, axis=0)
print(c.shape)

(1, 6)


# Indexing and Slicing

In [61]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


Dalam melakukan analisis mungkin kita akan mengambil bagian array atau elemen array.

In [62]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]
              ])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
# You can easly print all of the values in the array that are less than 5

print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [66]:
five_up=(a>=5)

print(a[five_up])
print(a[a>5])

[ 5  6  7  8  9 10 11 12]
[ 6  7  8  9 10 11 12]


In [68]:
# You can select elements that are divisible by 2

divisible_by_2=a[a%2==0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [70]:
# you can select elemen that satisfy two conditions using the and | operator"

c = a[(a>2)&(a<11)]
print(c)

[ 3  4  5  6  7  8  9 10]


# Creating Array from Existing Data

Kita dapat membuat array baaru dari bagian array yang sudah ada.

In [71]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [73]:
arr1= arr[3:8]
arr1

array([4, 5, 6, 7, 8])

Kita juga dapat menumpuk dua array yang ada, baik secara vertikal maupun horizontal

In [74]:
a_1=([[1,1],
     [2,2]])
a_2=([[3,3],
     [4,4]])

Menumpuk vertikal dengan **vstack**

In [76]:
np.vstack((a_1,a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [77]:
# or stack them horizontal with hstack

np.hstack((a_1,a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

Kita juga dapat membagi sebuah array menjadi beberapa array yang lebih kecil menggunakan hsplit. Kita dapat mennetukan jumlah array yang bentuknya sama untuk dikmebalikan atau kolom setelah pembagian dilakukan.

In [79]:
array_split=np.array([[1,2,3,4,5,6],
                    [7,8,9,10,11,12]])
print(array_split)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [81]:
# if you wanted to split this array into three equally shaped arrays
print(np.hsplit(array_split,3))

[array([[1, 2],
       [7, 8]]), array([[ 3,  4],
       [ 9, 10]]), array([[ 5,  6],
       [11, 12]])]


Metode view untuk membuat objek baru yang terlihat sama dengan array asli( shallow copy)

In [83]:
v = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
v

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [86]:
# You can create a new array object that looks at the same data

va=v.view()
va

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [88]:
# Using the copy method will make a complete copy of the array and its data ( a deep copy )
vb=v.copy()
vb

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Basic array operations

Menemukan penjumlahan hasil elemen dalam array dengan **sum()**

In [91]:
a = np.array([1,2,3,4])

# Add all of the elements in the array
a.sum()

10

Untuk menambahkan baris atau kolom dalam array 2D, kalian harus menentukan axis.

In [92]:
b = np.array([[1,1], [2,2]])
b

array([[1, 1],
       [2, 2]])

In [93]:
# You can sum the rows
b.sum(axis=0)

array([3, 3])

In [94]:
# You can sum the columns
b.sum(axis=1)

array([2, 4])

In [96]:
data = np.array([1,2])
data

array([1, 2])

In [97]:
ones = np.ones(2)
ones

array([1., 1.])

In [98]:
data + ones

array([2., 3.])

In [99]:
data * data

array([1, 4])

In [100]:
data / data

array([1., 1.])

# Broadcasting

ada kalanya ingin melakukan operai antara array dan stau bilangan ( juga disebut operasi antara vektor dan skalar) atau anatara array dengan dua ukuran berbeda.

Numpy memahami bahwa perkalian harus dilakukan dengan setiap sel. konspe itu disebut broadcasting.

Jadi Broadcasting adalah mekanisme yang memungkinkan 
numpy melakukan operasi pada array dengan bentuk berbeda

In [101]:
data * 2

array([2, 4])

# More Array Operations

Numpy juga melakukan fungsi agregasi. Selain min, max dan sum. juga bisa menjalaankan 
- mean untuk mendapatkan rata2, 
- proud untuk mendapatkan hasil perkalian elemen, 
- std untuk mendapatkan standart deviation

In [104]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [105]:
A.sum()

4.8595784

In [106]:
A.min()

0.05093587

In [107]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [108]:
A.max()

0.82485143

In [109]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [110]:
A.std()

0.21392120766089617

# Matrices

Kita dapat meneruskan listsof lists python untuk membuat matriks untuk mewakilinya di numpy

# Creating Matrices

kita juga dapat menggunakan metode yang sama selama kita memberi mereka tuple yangg menggambarkan dimensi matriks

In [114]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.77663993 0.5924969 ]
 [0.74020425 0.57809627]
 [0.97604798 0.96324549]]


# Matrix Arithmetic

Kita dapat menggunakan operator aritmatika jika kedua matriks berukuran sama. Numpy menaganninya sebagai position-wise operations

In [115]:
data = np.array([[1,2],[3,4]])
print("data")

data


In [116]:
ones=np.ones([2,2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [117]:
print(data+ones)

[[2. 3.]
 [4. 5.]]


In [118]:
ones_row=np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [119]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


# Dot Product

Numpy memberikan setiap matriks metode dot() untuk 
menjalankan operasi dot product dengan matriks lain

In [120]:
a_1 = np.array([[1,2,3],[4,5,6]])
print(a_1)
print(a_1.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [121]:
a_2 = np.array([[7,8],[9,10],[11,12]])
print(a_2)
print(a_2.shape)

[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [122]:
np.dot(a_1,a_2)

array([[ 58,  64],
       [139, 154]])

# Matrix Indexing

Operais indexing dan slicing menjadi lebih berguna saat kita memanipulai matriks

In [123]:
data = np.array([[1,2],[3,4],[5,6]])

In [124]:
print(data)
print(data[0])
print(data[1])
print(data[2])
print( data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


# Matrix Aggregation

In [125]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [126]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [127]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


# Transposing and Reshaping

Kebutuhan untuk rotate. Array numpy memiliki properti yang disebut T untuk mendapatkan transpose dari sebuah matriks

In [128]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [129]:
print(data.T)

[[1 3 5]
 [2 4 6]]


Metode **reshape()** Numpy berguna mengganti dimensi matriks

In [130]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [131]:
print(data_col.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [132]:
print(data_col.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


Menggunakan **np.Transpose** untuk mengembalikan/ mengembalikangubah axes array sesuai dengan nilai yang kalian tentukan

In [134]:
arr = np.arange(6).reshape((2,3))
print(arr)

[[0 1 2]
 [3 4 5]]


# N-Dimensional Array

In [135]:
ndarr = np.array([[[1, 2],[3, 4]],
                  [[5, 6],[7, 8]]])
print(ndarr)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Menambahkan dimensi baru dengan koma ke parameter fungsi NumPy

In [136]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [137]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [138]:
print(np.random.random((4,3,2)))

[[[0.89708008 0.39140448]
  [0.48056102 0.65195323]
  [0.74922481 0.93743243]]

 [[0.25929416 0.40343994]
  [0.34507807 0.88089292]
  [0.27688395 0.82040402]]

 [[0.07122346 0.70056204]
  [0.97257197 0.21743718]
  [0.22748531 0.0735217 ]]

 [[0.22846357 0.49782816]
  [0.01226557 0.56622885]
  [0.8797948  0.78150639]]]


# Flatten N-Dimensional Array

Dua cara utama untuk meratakan array : **flatten()** dan **ravel()**. Perbedaan utama antara keudanya adalah bahwa array baru yang dibuat menggunakan ravel() sebenarnya merupakan refrensi ke array induk. ini berarti bahwa setiap perubahan pada array baru akan memepengaruhi array induk juga. karena ravel tidak membuat salinan, menghemat memori

In [139]:
arrflat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrflat)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [140]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])